tests
testError
	
	"Just an example, never gets executed because of the exception"
	self assert: 3 / 0 equals: 0